"""initial

Revision ID: 71064b266f1d
Revises: 
Create Date: 2026-04-30 23:18:40.986236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71064b266f1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_types',
    sa.Column('crop_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scientific_name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('temp_min', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('temp_max', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('temp_optimal', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('humidity_min', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('humidity_max', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ph_min', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('ph_max', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('light_min_lux', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('light_max_lux', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('growth_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('crop_type_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('zones',
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('area_m2', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('zone_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('crops',
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('crop_type_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('batch_code', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('planted_at', sa.Date(), nullable=False),
    sa.Column('expected_harvest_at', sa.Date(), nullable=True),
    sa.Column('actual_harvest_at', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['crop_type_id'], ['crop_types.crop_type_id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.zone_id'], ),
    sa.PrimaryKeyConstraint('crop_id'),
    sa.UniqueConstraint('batch_code')
    )
    op.create_table('devices',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('registered_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=60), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('firmware_version', sa.String(length=20), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['registered_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.zone_id'], ),
    sa.PrimaryKeyConstraint('device_id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('sensor_readings',
    sa.Column('reading_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ph', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('light_lux', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('co2_ppm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('soil_moisture', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('reading_id')
    )
    op.create_table('alerts',
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('reading_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('measured_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('threshold_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['reading_id'], ['sensor_readings.reading_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('predictions',
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('reading_id', sa.BigInteger(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('predicted_class', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('raw_probabilities', sa.JSON(), nullable=True),
    sa.Column('input_features', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['reading_id'], ['sensor_readings.reading_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_table('alerts')
    op.drop_table('sensor_readings')
    op.drop_table('devices')
    op.drop_table('crops')
    op.drop_table('zones')
    op.drop_table('users')
    op.drop_table('crop_types')
    # ### end Alembic commands ###
